### Get All Clients
GET http://localhost:5031/api/clients
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Create a New Client
POST http://localhost:5031/api/clients
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "id": 1,
    "name": "John Doe Updated",
    "address": "123 Main St Updated",
    "city": "Anytown",
    "zipCode": "12345",
    "province": "Anyprovince",
    "country": "Anycountry",
    "contactName": "Jane Doe",
    "contactPhone": "555-1234",
    "contactEmail": "jane.doe@example.com"
}
