### Update an existing Client

PUT http://localhost:5031/api/clients/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "Id": 1,
  "Name": "Test Update",
  "Address": "123 Sinterklaas, Rotterdam, NY",
  "City": "Rotterdam",
  "ZipCode": "1234AB",
  "Province": "Zuid-Holland",
  "Country": "Netherlands",
  "ContactName": "Charlotte",
  "ContactPhone": "+1234567890",
  "ContactEmail": "charlotte@gmail.com"
}

### Update an existing inventory entry
PUT http://localhost:5031/api/inventories/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "id": 1,
  "ItemId": "New ID",
  "TotalOnHand": 100,
  "TotalExpected": 50,
  "TotalOrdered": 40,
  "TotalAllocated": 10,
  "TotalAvailable": 110,
  "Description": "Updated Description"
}

### Update an existing item group
PUT http://localhost:5031/api/item_groups/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "id": 1,
  "name": "Updated Name",
  "description": "Updated description for the category"
}

### Update an existing contact
PUT http://localhost:5031/api/contacts/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "Id": "1",
  "ContactName": "Updated Name",
  "ContactPhone": "123123123",
  "ContactEmail": "test@test.nl"
}


### Update an item
PUT http://localhost:5031/api/items/P001201
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "uid": "P001201",
  "code": "sjQ23408K",
  "description": "updated Item",
  "short_description": "updated item",
  "upc_code": "6523523427122",
  "model_number": "44-9JeF0S",
  "commodity_code": "Lwoak",
  "item_line": 15,
  "item_group": 80,
  "item_type": 14,
  "unit_purchase_quantity": 20,
  "unit_order_quantity": 12,
  "pack_order_quantity": 7,
  "supplier_id": 79,
  "supplier_code": "MSI902",
  "supplier_part_number": "A-75389-mNT"
}

### Update an existing location
PUT http://localhost:5031/api/locations/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "Id": 1,
  "WarehouseId": 1,
  "Code": "Z.5.1",
  "Name": "Test Update"
}

### Update an existing order
PUT http://localhost:5031/api/orders
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "Id": 1,
  "SourceId": 33,
  "OrderDate": "2019-04-03T11:33:15Z",
  "RequestDate": "2019-04-07T11:33:15Z",
  "Reference": "ORD00001",
  "ReferenceExtra": "Updated.",
  "OrderStatus": "Delivered",
  "Notes": "Changed.",
  "ShippingNotes": "Shipping notes.",
  "PickingNotes": "Pick up.",
  "WarehouseId": 18,
  "ShipTo": "Null",
  "BillTo": "Null",
  "ShipmentId": 1,
  "TotalAmount": 9905.13,
  "TotalDiscount": 150.77,
  "TotalTax": 372.72,
  "TotalSurcharge": 77.6,
    "Items": [
        {
            "Uid": "P00001",
            "Code": "P00001",
            "Description": "Updated 1",
            "ShortDescription": "Prod 1",
            "UpcCode": "123456789012",
            "ModelNumber": "123456",
            "CommodityCode": "123456",
            "item_line": 1,
            "item_group": 1,
            "item_type": 1,
            "supplier_id": 1
        }
    ]
}

### Update an existing shipment
PUT http://localhost:5031/api/shipments
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "Id": 4,
  "OrderId": 1,
  "SourceId": 33,
  "OrderDate": "2000-03-09",
  "RequestDate": "2000-03-11",
  "ShipmentDate": "2000-03-13",
  "ShipmentType": "I",
  "ShipmentStatus": "Pending",
  "Notes": "Updated notes.",
  "CarrierCode": "DPD",
  "CarrierDescription": "Description",
  "ServiceCode": "Fastest",
  "PaymentType": "Manual",
  "TransferMode": "Ground",
  "TotalPackageCount": 31,
  "TotalPackageWeight": 594.42,
    "Items": ["P00000"]
}

### Update an existing supplier
PUT http://localhost:5031/api/suppliers/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "Id": 1,
    "Code": "SUP0002",
    "Name": "Updated Supplier",
    "Address": "1234 Wijnhaven",
    "AddressExtra": "",
    "City": "Rotterdam",
    "ZipCode": "2342JK",
    "Province": "Zuid-Holland",
    "Country": "Netherlands",
    "ContactName": "Jur",
    "PhoneNumber": "01028903847",
    "Reference": "Smith-SUP0002"
}


### Update an existing transfer
PUT http://localhost:5031/api/transfers/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "Id": 1,
    "Reference": "T00001",
    "TransferFrom": 1,
    "TransferTo": 2,
    "TransferStatus": "Succeeded"
}

### Update an existing warehouse
PUT http://localhost:5031/api/warehouses/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "id": 1,
  "code": "YQZZNL56",
  "name": "Daniel's company",
  "address": "Wijnstraat 200",
  "zip": "2819 YW",
  "city": "Maastricht",
  "province": "Limburg",
  "country": "NL",
  "contact": {
    "name": "Daniel Nales",
    "phone": "(078) 0013363",
    "email": "Daniel@example.net"
  }
}

### Update an item type
PUT http://localhost:5031/api/item_types/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "id": 0,
    "name": "Updated Laptop",
    "description": "HP Laptop"
}

### Update an item line
PUT http://localhost:5031/api/item_lines/1
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "id": 1,
    "name": "updated Item Line",
    "description": "updated description item line"
}

### Update an item in a specific order
PUT http://localhost:5031/api/orders/1/items/P213132
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "uid": "P213132",
    "code": "12345",
    "description": "Updated Item Description",
    "short_description": "Updated Short Description",
    "upc_code": "UpdatedUPC123",
    "model_number": "UpdatedModel123",
    "commodity_code": "UpdatedCommodity123",
    "unit_purchase_quantity": 20,
    "unit_order_quantity": 15,
    "pack_order_quantity": 10,
    "supplier_id": 1,
    "supplier_code": "UpdatedSUP123",
    "supplier_part_number": "Updated-SPN12345"
}

