### Get all items of a specific item type
GET http://localhost:5031/api/items/by-item-type/14
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get all items of a specific item group
GET http://localhost:5031/api/items/by-item-group/80
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get all items of a specific item line
GET http://localhost:5031/api/items/by-item-line/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all warehouses
GET http://localhost:5031/api/warehouses
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all contacts
GET http://localhost:5031/api/contacts
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for contact with ID
GET http://localhost:5031/api/contacts/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for warehouses with ID
GET http://localhost:5031/api/warehouses/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all locations in warehouse by ID
GET http://localhost:5031/api/warehouses/1/locations
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all locations
GET http://localhost:5031/api/locations
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for locations by ID
GET http://localhost:5031/api/locations/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all transfers
GET http://localhost:5031/api/transfers
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for transfers by ID
GET http://localhost:5031/api/transfers/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get items for a transfer by transfer ID
GET http://localhost:5031/api/transfers/1/items
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all items
GET http://localhost:5031/api/items
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for items by ID
GET http://localhost:5031/api/items/P001201
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for inventory in item by ID
GET http://localhost:5031/api/items/P000001/inventory
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for total inventory in item by ID
GET http://localhost:5031/api/items/P000001/inventory/totals
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all item_lines
GET http://localhost:5031/api/item_lines
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for item_lines by ID
GET http://localhost:5031/api/item_lines/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for items in item_lines by ID
GET http://localhost:5031/api/item_lines/1/items
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all items_groups
GET http://localhost:5031/api/item_groups
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for items_groups by id
GET http://localhost:5031/api/item_groups/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for items in items_groups by ID
GET http://localhost:5031/api/item_groups/1/items
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all item_types
GET http://localhost:5031/api/item_types
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for item_types by ID
GET http://localhost:5031/api/item_types/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for items in item_types by ID
GET http://localhost:5031/api/item_types/1/items
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all inventories
GET http://localhost:5031/api/inventories
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for inventories by ID
GET http://localhost:5031/api/inventories/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all suppliers
GET http://localhost:5031/api/suppliers
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for suppliers by ID
GET http://localhost:5031/api/suppliers/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for items in suppliers by ID
GET http://localhost:5031/api/suppliers/1/items
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all orders
GET http://localhost:5031/api/orders
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for orders by ID
GET http://localhost:5031/api/orders/2
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for items in orders by ID
GET http://localhost:5031/api/orders/2/items
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all clients
GET http://localhost:5031/api/clients
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for clients by ID
GET http://localhost:5031/api/clients/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for orders in clients by ID
GET http://localhost:5031/api/clients/1/orders
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for all shipments
GET http://localhost:5031/api/shipments
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for shipments by ID
GET http://localhost:5031/api/shipments/1
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for orders in shipments by ID
GET http://localhost:5031/api/shipments/1/orders
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get for items in shipments by ID
GET http://localhost:5031/api/shipments/1/items
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

### Get all items for a specific supplier
GET http://localhost:5031/api/items/supplier/79
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f