### POST Request to add a new client
POST http://localhost:5031/api/clients
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "Id": 1,
  "Name": "Test Company",
  "Address": "123 Sinterklaas, Rotterdam, NY",
  "City": "Rotterdam",
  "ZipCode": "1234AB",
  "Province": "Zuid-Holland",
  "Country": "Netherlands",
  "ContactName": "Charlotte",
  "ContactPhone": "+1234567890",
    "ContactEmail": "charlotte@gmail.com"
}

### POST Request to add a new contact
POST http://localhost:5031/api/contacts
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "Id": "1",
  "ContactName": "Charlotte",
  "ContactPhone": "123123123",
  "ContactEmail": "test@test.nl"

}

### POST Request to add a new inventory entry
POST http://localhost:5031/api/inventories
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "Id": 1,
  "ItemId": "P000002",
  "TotalOnHand": 200,
  "TotalExpected": 150,
  "TotalOrdered": 40,
  "TotalAllocated": 10,
  "TotalAvailable": 110,
  "Description": "Jurchad Enterprise"
}

### Add a new item
POST http://localhost:5031/api/items
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "uid": "P001201",
  "code": "sjQ23408K",
  "description": "Item",
  "short_description": "item",
  "upc_code": "6523523427122",
  "model_number": "44-9JeF0S",
  "commodity_code": "Lwoak",
  "item_line": 1,
  "item_group": 80,
  "item_type": 14,
  "unit_purchase_quantity": 20,
  "unit_order_quantity": 12,
  "pack_order_quantity": 7,
  "supplier_id": 79,
  "supplier_code": "MSI902",
  "supplier_part_number": "A-75389-mNT"
}

### Add a new location
POST http://localhost:5031/api/locations
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "code": "C.5.2",
  "name": "Row: C, Rack: 5, Shelf: 2"
}

### Add a new order
POST http://localhost:5031/api/orders
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "Id": 1,
    "SourceId": 34,
    "OrderDate": "2024-09-17T10:00:00Z",
    "RequestDate": "2024-09-18T10:00:00Z",
    "Reference": "ORD00002",
    "ReferenceExtra": "Example reference text.",
    "OrderStatus": "Pending",
    "Notes": "Additional notes for the order.",
    "ShippingNotes": "Please deliver to the main office.",
    "PickingNotes": "Ensure items are picked in the correct order.",
    "WarehouseId": 19,
    "ShipTo": "null",
    "BillTo": "null",
    "ShipmentId": 2,
    "TotalAmount": 1234.56,
    "TotalDiscount": 50.00,
    "TotalTax": 123.45,
    "TotalSurcharge": 15.00,
    "Items": [
        {
            "Uid": "P00001",
            "Code": "P00001",
            "Description": "Product 1",
            "ShortDescription": "Prod 1",
            "UpcCode": "123456789012",
            "ModelNumber": "123456",
            "CommodityCode": "123456",
            "ItemLine": 1,
            "ItemGroup": 1,
            "ItemType": 1,
            "SupplierId": 1
        }
    ]
}

### Add a new shipment
POST http://localhost:5031/api/shipments
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

    {
    "Id": 1,
    "OrderId": 2,
    "SourceId": 34,
    "OrderDate": "2024-09-15",
    "RequestDate": "2024-09-16",
    "ShipmentDate": "2024-09-17",
    "ShipmentType": "O",
    "ShipmentStatus": "Shipped",
    "Notes": "New shipment with updated details.",
    "CarrierCode": "DHL",
    "CarrierDescription": "DHL Express",
    "ServiceCode": "Standard",
    "PaymentType": "Prepaid",
    "TransferMode": "Air",
    "TotalPackageCount": 45,
    "TotalPackageWeight": 755.60,
    "Items": [
        {
            "Uid": "P00001",
            "Code": "P00001",
            "Description": "Product 1",
            "ShortDescription": "Prod 1",
            "UpcCode": "123456789012",
            "ModelNumber": "123456",
            "CommodityCode": "123456",
            "ItemLine": 1,
            "ItemGroup": 1,
            "ItemType": 1,
            "SupplierId": 1
        }
    ]
}

### Add a new supplier
POST http://localhost:5031/api/suppliers
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "Id": 1,
    "Code": "SUP0002",
    "Name": "Jur & Co.",
    "Address": "1234 Wijnhaven",
    "AddressExtra": "",
    "City": "Rotterdam",
    "ZipCode": "2342JK",
    "Province": "Zuid-Holland",
    "Country": "Netherlands",
    "ContactName": "Jur",
    "PhoneNumber": "01028903847",
    "Reference": "Smith-SUP0002"
}

### Add a new transfer
POST http://localhost:5031/api/transfers
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "Id": 1,
    "Reference": "T00001",
    "TransferFrom": 1,
    "TransferTo": 2,
    "TransferStatus": "Pending",
    "Items": [
        {
            "Uid": "P00001",
            "Code": "P00001",
            "Description": "Product 1",
            "ShortDescription": "Prod 1",
            "UpcCode": "123456789012",
            "ModelNumber": "123456",
            "CommodityCode": "123456",
            "ItemLine": 1,
            "ItemGroup": 1,
            "ItemType": 1,
            "SupplierId": 1
        }
    ]
}

### Add a new warehouse
POST http://localhost:5031/api/warehouses
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "code": "XK9YJ7B3",
  "name": "Hogeschool Rotterdam",
  "address": "Wijnhaven 107",
  "zip": "2222 IO",
  "city": "Rotterdam",
  "province": "Zuid Holland",
  "country": "NL",
  "contact": {
    "name": "Harold",
    "phone": "(010) 1234567",
    "email": "Harold.devries@example.com"
  }
}

### Add a new item type
POST http://localhost:5031/api/item_types
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "id": 1,
    "name": "Laptop",
    "description": "Apple Macbook"
}

### Add a new item group
POST http://localhost:5031/api/itemgroups
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "id": 1,
    "name": "New Category",
    "description": "Description for new category"
}

### Add a new item line
POST http://localhost:5031/api/item_lines
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "id": 1,
    "name": "Item Line",
    "description": "Description item line"
}

