### POST Request to add a new client
POST http://localhost:5031/api/clients
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "name": "John Doe",
    "address": "123 Elm Street",
    "city": "Springfield",
    "zip_code": "12345",
    "province": "Illinois",
    "country": "USA",
    "contact_name": "Jane Doe",
    "contact_phone": "524-1234",
    "contact_email": "janeeeeee.doe@example.com"
}

### POST Request to add a new contact
POST http://localhost:5031/api/contacts
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "contact_name": "Harold",
  "contact_phone": "1231232223123",
  "contact_email": "tes2322t@test.nl"
}

### POST Request to add a new inventory entry
POST http://localhost:5031/api/inventories
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "item_id": 1,
    "locations": [1, 2],
    "total_on_hand": 50,
    "total_expected": 100,
    "total_ordered": 75,
    "total_allocated": 20,
    "total_available": 30
}


### Add a new item
POST http://localhost:5031/api/items
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
  "uid": "12345",
  "code": "sjQ23408K",
  "description": "New Item",
  "short_description": "item",
  "upc_code": "6523523427122",
  "model_number": "44-9JeF0S",
  "commodity_code": "Lwoak",
  "item_line": 1,
  "item_group": 80,
  "item_type": 14,
  "unit_purchase_quantity": 20,
  "unit_order_quantity": 12,
  "pack_order_quantity": 7,
  "supplier_id": 79,
  "supplier_code": "MSI902",
  "supplier_part_number": "A-75389-mNT"
}

### Add a new location
POST http://localhost:5031/api/locations
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "warehouse_id": 4,
    "code": "A.1.0",
    "name": "Row: B, Rack: 10000000, Shelf: 0"
}


### Add a new order
POST http://localhost:5031/api/orders
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "Id": 2,
    "source_id": 34,
    "order_date": "2024-09-17T10:00:00Z",
    "RequestDate": "2024-09-18T10:00:00Z",
    "Reference": "ORD00002",
    "ReferenceExtra": "Example reference text.",
    "order_status": "Pending",
    "Notes": "Additional notes for the order.",
    "ShippingNotes": "Please deliver to the main office.",
    "PickingNotes": "Ensure items are picked in the correct order.",
    "warehouse_id": 19,
    "ShipTo": "null",
    "bill_to": "null",
    "ShipmentId": 1,
    "TotalAmount": 1234.56,
    "TotalDiscount": 50.00,
    "TotalTax": 123.45,
    "TotalSurcharge": 15.00,
    "Items": [
        {
            "Uid": "P123",
            "Code": "P00001",
            "Description": "Product 1",
            "ShortDescription": "Prod 1",
            "UpcCode": "123456789012",
            "ModelNumber": "123456",
            "CommodityCode": "123456",
            "item_line": 1,
            "item_group": 1,
            "item_type": 1,
            "supplier_id": 1,
            "supplier_part_number": "asdf"
        }
    ]
}

### Add a new shipment
POST http://localhost:5031/api/shipments
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

    {
    "Id": 1,
    "order_id": 2,
    "source_id": 34,
    "OrderDate": "2024-09-15",
    "RequestDate": "2024-09-16",
    "ShipmentDate": "2024-09-17",
    "shipment_type": "O",
    "ShipmentStatus": "Shipped",
    "Notes": "New shipment with updated details.",
    "carrier_code": "DHL",
    "CarrierDescription": "DHL Express",
    "service_code": "Standard",
    "payment_type": "Prepaid",
    "transfer_mode": "Air",
    "TotalPackageCount": 45,
    "TotalPackageWeight": 755.60,
    "shipment_items": [
       { 
            "id": 1,
            "ItemUid": "P22222",
            "amount": 2
       }
    ]
}

### Add a new supplier
POST http://localhost:5031/api/suppliers
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "code": "SUP123",
    "name": "Global Supplies Inc.",
    "address": "123 Supplier Lane",
    "city": "Supply City",
    "zip_code": "12345",
    "province": "ProvinceLand",
    "country": "SupplyCountry",
    "contact_name": "John Supplier",
    "phone_number": "1234567890",
    "reference": "REF123"
}


### Add a new transfer
POST http://localhost:5031/api/transfers
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "reference": "T00001",
    "transferFrom": 1,
    "transferTo": 2,
    "transferStatus": "Pending",
    "transfer_items": [
        {
            "item_uid": "12345",  
            "amount": 5
        }
    ]
}


### Add a new warehouse
POST http://localhost:5031/api/warehouses
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "code": "AKFJAF-123",
    "name": "Main Warehouse",
    "address": "123 Warehouse Street",
    "zip": "45678",
    "city": "Metropolis",
    "province": "Central",
    "country": "USA",
    "contact": [
        {
            "contact_name": "John Doe",
            "contact_phone": "555-1234",
            "contact_email": "john.doe@example.com"
        },
        {
            "contact_name": "Jane Smith",
            "contact_phone": "555-5678",
            "contact_email": "jane.smith@example.com"
        }
    ],
    "created_at": "2025-01-16T12:00:00",
    "updated_at": null
}


### Add a new item type
POST http://localhost:5031/api/item_types
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "id": 14,
    "name": "Laptop",
    "description": "Apple Macbook"
}

### Add a new item group
POST http://localhost:5031/api/item_groups
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "id": 80,
    "name": "New Category",
    "description": "Description for new category"
}

### Add a new item line
POST http://localhost:5031/api/item_lines
Content-Type: application/json
X-API-KEY: 3f5e8b9c-2d4a-4b6a-8f3e-1a2b3c4d5e6f

{
    "name": "Item Line",
    "description": "Description item line",
    "created_at": "2024-09-17T10:00:00Z"
}

